[package]
name = "processor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
thiserror = "1.0.35"
dats = { path = "../dats" }
threadpool = "1.8.1"
serde = "1.0.180"
serde_yaml = "0.9.25"
specta = "1.0.5"
tokio = { version = "1.29.1", features = ["full"] }
walkdir = "2.4.0"
